language_index: dict = {
    "ru": 0,
    "en": 1
};

Actions_Solo = {
    "Сфотографируйте себя": "Take a picture of yourself",
    "Займитесь спортом": "Go in for sports",
    "Попробуйте снять видео на тематику, которую вы чаще всего смотрите": "Try to shoot a video on the topic that you most often watch",
    "Сходите в кафе, бар или ресторан": "Go to a cafe, bar or restaurant",
    "Слушайте музыку": "Listen to music",
    "Займитесь хобби. Если его нет - найдите его": "Take up a hobby. If it's not there, find it",
    "Начните коллекционировать какие-то вещи": "Start collecting some things",
    "Посмотрите образовательные курсы, которые могут пригодиться": "Check out the educational courses that may come in handy",
    "Посмотрите образовательные курсы по профессии, которую вам сгенерировал наш бот": "Check out the educational courses on the profession that our bot has generated for you",
    "Очень вкусно покушайте": "Have a very tasty meal",
    "Покатайтесь на велосипеде, самокате, скейте, роликах или машине": "Ride a bike, scooter, skateboard, roller skates or a car",
    "Навестите родственников или близких": "Visit relatives or loved ones",
    "Сходите погулять с друзьями": "Go for a walk with friends",
    "Отправьтесь куда глаза глядят на машине, автобусе или поезде": "Go wherever you want by car, bus or train",
    "Познакомьтесь с кем-нибудь в жизни или анонимном чате (можно и на сайтах знакомств)": "Meet someone in real life or in an anonymous chat (you can also on dating sites)",
    "Заведите домашнее животное. Если оно уже есть, то проведите время с ним": "Get a pet. If it already exists, then spend time with it",
    "Узнайте способ подработать денег": "Find out a way to earn some money",
    "Сходите на какой-нибудь концерт или фестиваль": "Go to some concert or festival",
    "Прочитайте книгу о бизнесе": "Read a book about business",
    "Прочитайте книгу о любви": "Read a book about love",
    "Прочитайте детектив": "Read the detective",
    "Прочитайте утопию/антиутопию": "Read Utopia/Dystopia",
    "Прочитайте комедию": "Read the comedy",
    "Прочитайте драму": "Read the drama",
    "Прочитайте научную фантастику": "Read science fiction",
    "Прочитайте ужасы": "Read the horrors",
    "Прочитайте техническую литературу": "Read the technical literature",
    "Посмотрите фильм о бизнесе": "Watch a movie about business",
    "Посмотрите фильм о любви": "Watch a movie about love",
    "Посмотрите детектив": "Watch the detective",
    "Посмотрите утопию/антиутопию": "Watch Utopia/Dystopia",
    "Посмотрите комедию": "Watch the comedy",
    "Посмотрите драму": "Watch the drama",
    "Посмотрите научную фантастику": "Watch science fiction",
    "Посмотрите ужасы": "Watch the horrors",
    "Посмотрите триллер": "Watch the thriller",
    "Посмотрите шутер": "Watch the shooter",
    "Покормите голубей, белок или уток в парке": "Feed pigeons, squirrels or ducks in the park",
    "Подумайте над тем, как можно изменить мир": "Think about how you can change the world",
    "Полюбуйтесь видом (из окна или на какой-то возвышенности)": "Admire the view (from the window or on some hill)",
    "Уберитесь дома. Выбросьте все ненужное": "Clean up the house. Throw away everything unnecessary",
    "Составьте и запишите ваш план на жизнь": "Make and write down your life plan",
    "Пройдитесь по магазинам и купите себе чего-нибудь": "Go shopping and buy yourself something",
    "Напишите свою книгу, статью или рассказ": "Write your book, article or story",
    "Насладитесь природой! Посмотрите на закат, рассвет, звезды, облака или просто небо": "Enjoy nature! Look at the sunset, sunrise, stars, clouds or just the sky",
    "Побудьте волонтером": "Be a volunteer",
    "Научитесь играть на музыкальном инструменте": "Learn to play a musical instrument",
    "Научитесь создавать и микшировать музыку": "Learn how to create and mix music",
    "Насладитесь Тишиной": "Enjoy the Silence",
    "Посмотрите в запой какой-нибудь сериал": "Watch some TV series in its entirety",
    "Найдите интересные мероприятия для посещения": "Find interesting events to attend",
    "Нарисуйте что-нибудь": "Draw something",
    "Займитесь чем-нибудь творческим": "Do something creative",
    "Научитесь танцевать": "Learn to dance",
    "Попробуйте экстремальный отдых": "Try an extreme vacation",
    "Сделайте что-нибудь своими руками": "Do something with your own hands",
    "Подтяните иностранный язык или начните изучать новый": "Remember a foreign language or start learning a new one",
    "Посмотрите спортивный матч или состязание, а лучше сходите на стадион или арену": "Watch a sports match or a competition, or better yet, go to the stadium or arena",
    "Сходите на экскурсию, на выставку, в музей, театр или кино": "Go on an excursion, to an exhibition, to a museum, theater or cinema",
    "Начните работать": "Start working",
    "Искупайтесь или сходите в сауну": "Take a swim or go to the sauna",
    "Съездите на дачу или в деревню": "Go to the suburb or to the village",
    "Подпишись на интересных людей, чтобы почерпнуть что-то нового. Например, на @echosdev или @echostoday": "Subscribe to interesting people to learn something new. For example, on @echosdev or @echostoday",
    "Отправлтесь в самые тусовочные места вашего города": "Go to a party",
    "Поддайтесь искушению": "Give in to temptation",
    "Побродите по барахолке и блошиным рынкам": "Wander through flea markets",
    "Сделайте что-то хорошее и доброе": "Do something good and kind",
    "Подарите кому-то подарок": "Give someone a gift",
    "Избавьтесь от одной или нескольких вредных привычек, но приобретите полезные": "Get rid of one or more bad habits, but acquire useful ones",
    "Смените свой стиль, займитесь своей внешностью": "Change your style, take care of your appearance",
    "Составьте список идей и планов": "Make a list of ideas and plans",
    "Поработайте над манерами и этикой": "Work on manners and ethics",
    "Напишите письмо будущему себе": "Write a letter to your future self",
    "Научитесь делать трюки. Сальто, например": "Learn to do tricks. Somersaults, for example",
    "Научитесь кататься на скейтборде": "Learn to ride a skateboard",
    "Научитесь готовить": "Learn how to cook",
    "Бросьте сам себе вызов или пообещайте что-то": "Challenge yourself or promise something",
    "Задумайтесь о переезде или смене образа жизни": "Think about moving or changing your lifestyle",
    "Играйте в компьютерные игры!": "Play computer games!",
    "Разложите пасьянс": "Play Solitaire",
    "Сыграйте в сапера": "Play Minesweeper",
    "Разгадайте сканворд, ребус": "Solve the crossword, Rebus",
    "Решайте тесты": "Solve tests",
    "Пройдите медицинское обследование": "Go through a medical examination",
    "Составьте новый плейлист": "Make a new playlist",
    "Продайте что-то": "Sell something",
    "Закажите суши или пиццу": "Order sushi or pizza",
    "Покатайтесь или побродите по ночному городу": "Take a ride or wander around the city at night",
    "Отправляйтесь в интернет в поисках халявы. Например, найдите бесплатное мероприятие": "Go online in search of freebies. For example, find a free event",
    "Научитесь слепой печати": "Learn how to blind print",
    "Начните программировать": "Start coding",
    "Займитесь 3D графикой": "Engage in 3D graphics",
    "Нарисуйте свой мультфильм": "Draw your own cartoon",
    "Сделайте автопортрет": "Make a self-portrait",
    "Напишите автобиографию": "Write an autobiography",
    "Сходить в туалет": "Go to the toilet",
    "Задонатить в игру": "Donate to the game",
    "Если вы играете в мобы, то посмотрите гайд на нового персонажа и научитесь на нем играть": "If you play mobs, then look at the guide for a new character and learn how to play it",
    "Полистайте списки бесплатных игр": "Scroll through the lists of free games",
    "Найдите для себя новую игру": "Find a new game for yourself",
    "Постарайтесь избавиться от прокрастинации": "Try to get rid of procrastination",
};